version: '3.8'

services:
  jenkins-server:
    container_name: jenkins-server
    image: jenkins/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-network
      - wan

  jenkins-slave:
    image: lioragent:1
    init: true
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_SECRET=f2c5d4fb308e28b3bf008572b56d0a8d328263e4f1ecace34214fcee44a9e3a3
      - JENKINS_AGENT_NAME=agent
    networks:
      - lan
    restart: always

networks:
  jenkins-network:
    driver: bridge

  wan:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"

  lan:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "192.168.11.0/24"




